-- Shared ICP document. Domain Waterfall ensure_profile writes this row.
-- People Waterfall only reads it (plus receipt-written tier_order / rates).

CREATE TABLE IF NOT EXISTS public.wf_client_profiles (
  client_tag text PRIMARY KEY,
  profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  target_titles jsonb,
  title_synonyms jsonb,
  title_exclude_regex text,
  seniority_floor text,
  fallback_titles jsonb,
  geo jsonb,
  company_size jsonb,
  employee_profiles_min integer,
  employee_profiles_max integer,
  ground_truth jsonb,
  cache_tables jsonb,
  tier_order jsonb,
  dropped_tiers jsonb,
  measured_rates jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.wf_client_profiles ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.pw_read_api_keys()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'private', 'public'
AS $function$
DECLARE
  result jsonb;
BEGIN
  SELECT coalesce(jsonb_agg(jsonb_build_object('name', name, 'value', value)), '[]'::jsonb)
    INTO result
  FROM private.api_keys;
  RETURN result;
END;
$function$;

REVOKE ALL ON FUNCTION public.pw_read_api_keys() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pw_read_api_keys() TO service_role;

CREATE OR REPLACE FUNCTION public.pw_ensure_people_writeback(
  p_schema text,
  p_table text
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  sch text;
  tbl text;
BEGIN
  sch := lower(regexp_replace(coalesce(p_schema, 'public'), '[^a-z0-9_]', '', 'g'));
  tbl := lower(regexp_replace(coalesce(p_table, ''), '[^a-z0-9_]', '', 'g'));
  IF sch = '' OR tbl = '' OR to_regclass(format('%I.%I', sch, tbl)) IS NULL THEN
    RAISE EXCEPTION 'unknown source table %.%', sch, tbl;
  END IF;
  EXECUTE format(
    'ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS wf_people_count integer',
    sch, tbl
  );
  EXECUTE format(
    'ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS wf_people_source text',
    sch, tbl
  );
  EXECUTE format(
    'ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS wf_people_status text',
    sch, tbl
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.pw_ensure_contacts_columns(
  p_table text
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  tbl text;
BEGIN
  tbl := lower(regexp_replace(coalesce(p_table, ''), '[^a-z0-9_]', '', 'g'));
  IF tbl = '' OR to_regclass(format('public.%I', tbl)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE public.%I (
         id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         first_name text,
         last_name text,
         job_title text,
         title_match boolean,
         title_rank integer,
         linkedin_url text,
         domain text,
         company_name text,
         source_tier text,
         source_confidence double precision,
         phone text,
         person_city text,
         person_state text,
         client_tag text,
         created_at timestamptz NOT NULL DEFAULT now(),
         updated_at timestamptz NOT NULL DEFAULT now()
       )',
      tbl
    );
    RETURN;
  END IF;
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS first_name text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS last_name text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS job_title text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS title_match boolean', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS title_rank integer', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS linkedin_url text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS domain text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS company_name text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS source_tier text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS source_confidence double precision', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS phone text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS person_city text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS person_state text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS client_tag text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()', tbl);
END;
$function$;
