-- Server-side ingest used when the agent VM has no service-role key.
-- Empty domain is stored as '' (wf_contacts.domain and name_bank.domain are NOT NULL).

CREATE TABLE IF NOT EXISTS public.pw_people_staging (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_tag text NOT NULL,
  first_name text,
  last_name text,
  job_title text,
  title_match boolean,
  title_rank integer,
  linkedin_url text,
  domain text,
  company_name text,
  source_tier text,
  source_confidence double precision,
  phone text,
  person_city text,
  person_state text,
  company_match boolean,
  is_current boolean,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.pw_ingest_people(p_client_tag text, p_rows jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  contacts_table text := format('%s_wf_contacts', p_client_tag);
  inserted int := 0;
  banked int := 0;
  r jsonb;
  exists_n int;
  v_domain text;
BEGIN
  IF p_client_tag !~ '^[a-z0-9_]+$' THEN
    RAISE EXCEPTION 'invalid client_tag';
  END IF;
  PERFORM public.pw_ensure_contacts_columns(contacts_table);

  FOR r IN SELECT * FROM jsonb_array_elements(p_rows)
  LOOP
    v_domain := coalesce(nullif(lower(trim(r->>'domain')), ''), '');

    INSERT INTO public.pw_people_staging (
      client_tag, first_name, last_name, job_title, title_match, title_rank,
      linkedin_url, domain, company_name, source_tier, source_confidence,
      phone, person_city, person_state, company_match, is_current
    ) VALUES (
      p_client_tag,
      nullif(r->>'first_name',''),
      nullif(r->>'last_name',''),
      nullif(r->>'job_title',''),
      coalesce((r->>'title_match')::boolean, false),
      nullif(r->>'title_rank','')::int,
      nullif(r->>'linkedin_url',''),
      v_domain,
      nullif(r->>'company_name',''),
      coalesce(nullif(r->>'source_tier',''), 'getleads'),
      coalesce(nullif(r->>'source_confidence','')::float8, 1.0),
      nullif(r->>'phone',''),
      nullif(r->>'person_city',''),
      nullif(r->>'person_state',''),
      coalesce((r->>'company_match')::boolean, true),
      CASE WHEN r ? 'is_current' THEN (r->>'is_current')::boolean ELSE NULL END
    );

    IF coalesce((r->>'title_match')::boolean, false)
       AND coalesce((r->>'company_match')::boolean, true) THEN
      EXECUTE format(
        'SELECT count(*) FROM public.%I WHERE lower(coalesce(domain, %L)) = lower(coalesce($1, %L)) AND lower(coalesce(first_name, %L)) = lower(coalesce($2, %L)) AND lower(coalesce(last_name, %L)) = lower(coalesce($3, %L))',
        contacts_table, '', '', '', '', '', ''
      ) INTO exists_n USING v_domain, r->>'first_name', r->>'last_name';
      IF exists_n = 0 THEN
        EXECUTE format(
          'INSERT INTO public.%I (first_name, last_name, job_title, title_match, title_rank, linkedin_url, domain, company_name, source_tier, source_confidence, phone, person_city, person_state, client_tag, source_tool, confidence, cellphone, contact_city, contact_state, updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,%L,$10,$11,$12,$13, now())',
          contacts_table, 'people-waterfall'
        ) USING
          nullif(r->>'first_name',''),
          nullif(r->>'last_name',''),
          nullif(r->>'job_title',''),
          true,
          nullif(r->>'title_rank','')::int,
          nullif(r->>'linkedin_url',''),
          v_domain,
          nullif(r->>'company_name',''),
          coalesce(nullif(r->>'source_tier',''), 'getleads'),
          coalesce(nullif(r->>'source_confidence','')::float8, 1.0),
          nullif(r->>'phone',''),
          nullif(r->>'person_city',''),
          nullif(r->>'person_state',''),
          p_client_tag;
        inserted := inserted + 1;
      END IF;
    ELSE
      INSERT INTO public.name_bank (
        client_tag, domain, first_name, last_name, job_title, linkedin_url, source, status
      ) VALUES (
        p_client_tag,
        v_domain,
        coalesce(nullif(r->>'first_name',''), '?'),
        coalesce(nullif(r->>'last_name',''), '?'),
        nullif(r->>'job_title',''),
        nullif(r->>'linkedin_url',''),
        coalesce(nullif(r->>'source_tier',''), 'getleads'),
        'wrong_title'
      )
      ON CONFLICT (client_tag, domain, first_name, last_name) DO NOTHING;
      banked := banked + 1;
    END IF;
  END LOOP;

  RETURN jsonb_build_object(
    'inserted', inserted,
    'name_bank', banked,
    'received', jsonb_array_length(p_rows)
  );
END;
$$;
