-- Style D may copy a published email pattern onto the contact row.

CREATE OR REPLACE FUNCTION public.pw_ensure_contacts_columns(
  p_table text
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  tbl text;
BEGIN
  tbl := lower(regexp_replace(coalesce(p_table, ''), '[^a-z0-9_]', '', 'g'));
  IF tbl = '' OR to_regclass(format('public.%I', tbl)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE public.%I (
         id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         first_name text,
         last_name text,
         job_title text,
         title_match boolean,
         title_rank integer,
         linkedin_url text,
         domain text,
         company_name text,
         source_tier text,
         source_confidence double precision,
         phone text,
         person_city text,
         person_state text,
         email text,
         client_tag text,
         created_at timestamptz NOT NULL DEFAULT now(),
         updated_at timestamptz NOT NULL DEFAULT now()
       )',
      tbl
    );
    RETURN;
  END IF;
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS first_name text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS last_name text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS job_title text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS title_match boolean', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS title_rank integer', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS linkedin_url text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS domain text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS company_name text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS source_tier text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS source_confidence double precision', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS phone text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS person_city text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS person_state text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS email text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS client_tag text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()', tbl);
END;
$function$;
