-- Upsert contacts on (client_tag, domain, lower(first_name), lower(last_name)).
-- PostgREST ON CONFLICT cannot target an expression index, so the lower
-- names are stored columns. Existing duplicates are removed first: keep the
-- best (lowest) title_rank, then the earliest physical row.

CREATE OR REPLACE FUNCTION public.pw_ensure_contacts_columns(
  p_table text
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  tbl text;
  idx text;
BEGIN
  tbl := lower(regexp_replace(coalesce(p_table, ''), '[^a-z0-9_]', '', 'g'));
  IF tbl = '' THEN
    RAISE EXCEPTION 'contacts table name is required';
  END IF;
  IF to_regclass(format('public.%I', tbl)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE public.%I (
         id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         first_name text,
         last_name text,
         first_name_key text,
         last_name_key text,
         job_title text,
         title_match boolean,
         title_rank integer,
         linkedin_url text,
         domain text,
         company_name text,
         source_tier text,
         source_confidence double precision,
         phone text,
         person_city text,
         person_state text,
         email text,
         client_tag text,
         created_at timestamptz NOT NULL DEFAULT now(),
         updated_at timestamptz NOT NULL DEFAULT now()
       )',
      tbl
    );
  END IF;
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS first_name text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS last_name text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS first_name_key text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS last_name_key text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS job_title text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS title_match boolean', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS title_rank integer', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS linkedin_url text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS domain text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS company_name text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS source_tier text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS source_confidence double precision', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS phone text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS person_city text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS person_state text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS email text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS client_tag text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()', tbl);
  EXECUTE format(
    'UPDATE public.%I
        SET domain = lower(coalesce(domain, ''''))
      WHERE domain IS DISTINCT FROM lower(coalesce(domain, ''''))',
    tbl
  );
  EXECUTE format(
    'UPDATE public.%I
        SET first_name_key = lower(coalesce(first_name, '''')),
            last_name_key = lower(coalesce(last_name, ''''))
      WHERE first_name_key IS DISTINCT FROM lower(coalesce(first_name, ''''))
         OR last_name_key IS DISTINCT FROM lower(coalesce(last_name, ''''))',
    tbl
  );
  EXECUTE format(
    'DELETE FROM public.%1$I a
      USING public.%1$I b
      WHERE a.ctid <> b.ctid
        AND coalesce(a.client_tag, '''') = coalesce(b.client_tag, '''')
        AND coalesce(a.domain, '''') = coalesce(b.domain, '''')
        AND coalesce(a.first_name_key, '''') = coalesce(b.first_name_key, '''')
        AND coalesce(a.last_name_key, '''') = coalesce(b.last_name_key, '''')
        AND (
          coalesce(a.title_rank, 2147483647) > coalesce(b.title_rank, 2147483647)
          OR (
            coalesce(a.title_rank, 2147483647) = coalesce(b.title_rank, 2147483647)
            AND a.ctid > b.ctid
          )
        )',
    tbl
  );
  idx := tbl || '_person_uidx';
  EXECUTE format(
    'CREATE UNIQUE INDEX IF NOT EXISTS %I
       ON public.%I (client_tag, domain, first_name_key, last_name_key)',
    idx,
    tbl
  );
END;
$function$;
