-- Persist site_staff quality fields: honorific, email_type, page_url.

CREATE OR REPLACE FUNCTION public.pw_ensure_contact_quality_columns(
  p_schema text,
  p_table text
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  sch text;
  tbl text;
BEGIN
  sch := lower(regexp_replace(coalesce(p_schema, 'public'), '[^a-z0-9_]', '', 'g'));
  tbl := lower(regexp_replace(coalesce(p_table, ''), '[^a-z0-9_]', '', 'g'));
  IF sch = '' OR tbl = '' OR to_regclass(format('%I.%I', sch, tbl)) IS NULL THEN
    RETURN;
  END IF;
  EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS email_type text', sch, tbl);
  EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS page_url text', sch, tbl);
  EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS honorific text', sch, tbl);
END;
$function$;

CREATE OR REPLACE FUNCTION public.pw_ensure_contacts_columns(
  p_table text
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  tbl text;
  idx text;
BEGIN
  tbl := lower(regexp_replace(coalesce(p_table, ''), '[^a-z0-9_]', '', 'g'));
  IF tbl = '' THEN
    RAISE EXCEPTION 'contacts table name is required';
  END IF;
  IF to_regclass(format('public.%I', tbl)) IS NULL THEN
    EXECUTE format(
      'CREATE TABLE public.%I (
         id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         first_name text,
         last_name text,
         first_name_key text,
         last_name_key text,
         job_title text,
         title_match boolean,
         title_rank integer,
         linkedin_url text,
         domain text,
         company_name text,
         source_tier text,
         source_confidence double precision,
         phone text,
         person_city text,
         person_state text,
         email text,
         email_type text,
         page_url text,
         honorific text,
         client_tag text,
         created_at timestamptz NOT NULL DEFAULT now(),
         updated_at timestamptz NOT NULL DEFAULT now()
       )',
      tbl
    );
  END IF;
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS first_name text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS last_name text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS first_name_key text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS last_name_key text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS job_title text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS title_match boolean', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS title_rank integer', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS linkedin_url text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS domain text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS company_name text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS source_tier text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS source_confidence double precision', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS phone text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS person_city text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS person_state text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS email text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS email_type text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS page_url text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS honorific text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS client_tag text', tbl);
  EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()', tbl);
  PERFORM public.pw_ensure_contact_quality_columns('public', tbl);
  EXECUTE format(
    'UPDATE public.%I
        SET domain = lower(coalesce(domain, ''''))
      WHERE domain IS DISTINCT FROM lower(coalesce(domain, ''''))',
    tbl
  );
  EXECUTE format(
    'UPDATE public.%I
        SET first_name_key = lower(coalesce(first_name, '''')),
            last_name_key = lower(coalesce(last_name, ''''))
      WHERE first_name_key IS DISTINCT FROM lower(coalesce(first_name, ''''))
         OR last_name_key IS DISTINCT FROM lower(coalesce(last_name, ''''))',
    tbl
  );
  EXECUTE format(
    'DELETE FROM public.%1$I a
      USING public.%1$I b
      WHERE a.ctid <> b.ctid
        AND coalesce(a.client_tag, '''') = coalesce(b.client_tag, '''')
        AND coalesce(a.domain, '''') = coalesce(b.domain, '''')
        AND coalesce(a.first_name_key, '''') = coalesce(b.first_name_key, '''')
        AND coalesce(a.last_name_key, '''') = coalesce(b.last_name_key, '''')
        AND (
          coalesce(a.title_rank, 2147483647) > coalesce(b.title_rank, 2147483647)
          OR (
            coalesce(a.title_rank, 2147483647) = coalesce(b.title_rank, 2147483647)
            AND a.ctid > b.ctid
          )
        )',
    tbl
  );
  idx := tbl || '_person_uidx';
  EXECUTE format(
    'CREATE UNIQUE INDEX IF NOT EXISTS %I
       ON public.%I (client_tag, domain, first_name_key, last_name_key)',
    idx,
    tbl
  );
END;
$function$;

CREATE OR REPLACE FUNCTION public.pw_insert_contacts(
  p_schema text,
  p_table text,
  p_rows jsonb
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  sch text;
  tbl text;
  rec jsonb;
  existing text[];
  wanted text[] := ARRAY[
    'client_tag', 'domain', 'first_name', 'last_name', 'job_title', 'email',
    'email_type', 'page_url', 'honorific', 'title_match', 'title_rank', 'company_name',
    'source', 'source_url', 'source_tier', 'source_confidence', 'linkedin_url',
    'phone', 'person_city', 'person_state', 'cellphone', 'contact_city',
    'contact_state', 'confidence', 'source_tool', 'updated_at'
  ];
  use_cols text[];
  col text;
  col_sql text;
  val_sql text;
  inserted integer := 0;
  found integer;
  tag text;
  dom text;
  fname text;
  lname text;
  raw text;
BEGIN
  sch := lower(regexp_replace(coalesce(p_schema, 'public'), '[^a-z0-9_]', '', 'g'));
  tbl := lower(regexp_replace(coalesce(p_table, ''), '[^a-z0-9_]', '', 'g'));
  IF sch = '' OR tbl = '' OR to_regclass(format('%I.%I', sch, tbl)) IS NULL THEN
    RAISE EXCEPTION 'unknown contacts table %.%', sch, tbl;
  END IF;

  PERFORM public.pw_ensure_contact_quality_columns(sch, tbl);
  EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS title_match boolean', sch, tbl);
  EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS title_rank integer', sch, tbl);
  EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS company_name text', sch, tbl);
  EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS source text', sch, tbl);
  EXECUTE format('ALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS source_url text', sch, tbl);

  SELECT array_agg(c.column_name)
    INTO existing
  FROM information_schema.columns c
  WHERE c.table_schema = sch AND c.table_name = tbl;

  use_cols := ARRAY(
    SELECT u
    FROM unnest(wanted) AS u
    WHERE u = ANY (existing)
  );

  FOR rec IN SELECT * FROM jsonb_array_elements(coalesce(p_rows, '[]'::jsonb))
  LOOP
    tag := coalesce(rec->>'client_tag', '');
    dom := lower(coalesce(rec->>'domain', ''));
    fname := lower(coalesce(rec->>'first_name', ''));
    lname := lower(coalesce(rec->>'last_name', ''));
    IF tag = '' OR dom = '' OR fname = '' THEN
      CONTINUE;
    END IF;
    EXECUTE format(
      'SELECT 1 FROM %I.%I WHERE client_tag = $1 AND lower(coalesce(domain, '''')) = $2 AND lower(coalesce(first_name, '''')) = $3 AND lower(coalesce(last_name, '''')) = $4 LIMIT 1',
      sch, tbl
    ) INTO found USING tag, dom, fname, lname;
    IF found = 1 THEN
      CONTINUE;
    END IF;

    col_sql := '';
    val_sql := '';
    FOREACH col IN ARRAY use_cols
    LOOP
      raw := rec->>col;
      IF col_sql <> '' THEN
        col_sql := col_sql || ', ';
        val_sql := val_sql || ', ';
      END IF;
      col_sql := col_sql || format('%I', col);
      IF col = 'updated_at' THEN
        val_sql := val_sql || 'now()';
      ELSIF raw IS NULL OR raw = '' THEN
        val_sql := val_sql || 'NULL';
      ELSIF col = 'title_match' THEN
        val_sql := val_sql || format('%L::boolean', raw);
      ELSIF col = 'title_rank' THEN
        val_sql := val_sql || format('%L::integer', raw);
      ELSIF col IN ('source_confidence', 'confidence') THEN
        val_sql := val_sql || format('%L::double precision', raw);
      ELSE
        val_sql := val_sql || format('%L', raw);
      END IF;
    END LOOP;
    IF col_sql = '' THEN
      CONTINUE;
    END IF;
    EXECUTE format('INSERT INTO %I.%I (%s) VALUES (%s)', sch, tbl, col_sql, val_sql);
    inserted := inserted + 1;
  END LOOP;
  RETURN inserted;
END;
$function$;
