-- NOT RUN. Review only.
-- LeadMagic people tiers are gone. Set goliath's explicit order to the new
-- default. Profiles with null/empty people_tier_order inherit the code
-- default (site_staff → cache → discolike → prospeo_search → aiark_people)
-- and are left untouched here.
--
-- Does NOT touch dl_status, sg_exclude, or skip_* on any table.
-- Does NOT rewrite pull_receipts, lead_provenance, or CHECK constraints.

begin;

update public.wf_client_profiles
set
  people_tier_order = '[
    {"tier":"site_staff","billing":"free"},
    {"tier":"cache","billing":"free"},
    {"tier":"discolike","billing":"always"},
    {"tier":"prospeo_search","billing":"always"},
    {"tier":"aiark_people","billing":"per_result"}
  ]'::jsonb,
  profile = jsonb_set(
    coalesce(profile, '{}'::jsonb),
    '{people_tier_order}',
    '[
      {"tier":"site_staff","billing":"free"},
      {"tier":"cache","billing":"free"},
      {"tier":"discolike","billing":"always"},
      {"tier":"prospeo_search","billing":"always"},
      {"tier":"aiark_people","billing":"per_result"}
    ]'::jsonb
  ),
  updated_at = now()
where client_tag = 'goliath';

-- goliath profile->tier_order is a 005 artifact: a people-shaped object
-- list. Domain Waterfall would read it as an order of names it does not
-- know. Remove it. Do not touch string domain orders on other profiles.
update public.wf_client_profiles
set profile = profile - 'tier_order'
where client_tag = 'goliath'
  and jsonb_typeof(profile->'tier_order'->0) = 'object';

-- Optional: persist AI Ark person id so Email Waterfall can export/single
-- by id. Safe ADD COLUMN. Never touches dl_status / sg_exclude / skip_*.
create or replace function public.pw_ensure_contacts_columns(
  p_table text
) returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  tbl text;
  idx text;
begin
  tbl := lower(regexp_replace(coalesce(p_table, ''), '[^a-z0-9_]', '', 'g'));
  if tbl = '' then
    raise exception 'contacts table name is required';
  end if;
  if to_regclass(format('public.%I', tbl)) is null then
    execute format(
      'CREATE TABLE public.%I (
         id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         first_name text,
         last_name text,
         first_name_key text,
         last_name_key text,
         job_title text,
         title_match boolean,
         title_rank integer,
         linkedin_url text,
         aiark_person_id text,
         domain text,
         company_name text,
         source_tier text,
         source_confidence double precision,
         phone text,
         person_city text,
         person_state text,
         email text,
         client_tag text,
         created_at timestamptz NOT NULL DEFAULT now(),
         updated_at timestamptz NOT NULL DEFAULT now()
       )',
      tbl
    );
  end if;
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS first_name text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS last_name text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS first_name_key text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS last_name_key text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS job_title text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS title_match boolean', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS title_rank integer', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS linkedin_url text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS aiark_person_id text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS domain text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS company_name text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS source_tier text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS source_confidence double precision', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS phone text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS person_city text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS person_state text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS email text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS client_tag text', tbl);
  execute format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now()', tbl);
  execute format(
    'UPDATE public.%I
        SET domain = lower(coalesce(domain, ''''))
      WHERE domain IS DISTINCT FROM lower(coalesce(domain, ''''))',
    tbl
  );
  execute format(
    'UPDATE public.%I
        SET first_name_key = lower(coalesce(first_name, '''')),
            last_name_key = lower(coalesce(last_name, ''''))
      WHERE first_name_key IS DISTINCT FROM lower(coalesce(first_name, ''''))
         OR last_name_key IS DISTINCT FROM lower(coalesce(last_name, ''''))',
    tbl
  );
  idx := tbl || '_person_uidx';
  execute format(
    'CREATE UNIQUE INDEX IF NOT EXISTS %I
       ON public.%I (client_tag, domain, first_name_key, last_name_key)',
    idx,
    tbl
  );
end;
$function$;

commit;

-- Other 10 profiles (deep_roots, emcor, ifca_manhattan, nutter, nutter_hr,
-- peterson_earthworks, peterson_roof, salesglider_trades, sg_subs,
-- sg_subs_owners) have null/empty people_tier_order and inherit
-- DEFAULT_ORDER from code. Do not write those rows.
